### ISSUE TITLE
Stop requiring projects to use Cask

### ISSUE THREAD

**Issue by DamienCassou** [emacs-elsa/flycheck-elsa#2]
flycheck-elsa requires that a project is described with Cask. I don't understand the reasoning. I see many projects not having a Cask file. Out of the 210 packages I'm currently using, only 67 have a Cask file at the root.

**Comment by Fuco1** [comment]
Well that's how it is.  You can add the Cask file yourself.  I use this to have clean separate independent environments and Cask makes this easy and does it very well.

**Comment by Fuco1** [comment]
The reasoning for Cask is described in this thread: https://github.com/melpa/melpa/pull/5769
